services:
  featureflag:
    image: featureflag
    build:
      context: .
      dockerfile: FeatureFlag.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - database
      - cache
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Username=postgres;Password=postgres;Database=featureflag
      - Redis__Configuration=redis:6379

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: featureflag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/database:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
  
