version: '3.8'

volumes:
  pgdata: {}

services:
  featureflag:
    image: featureflag
    container_name: featureflag
    build:
      context: .
      dockerfile: FeatureFlag.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ConnectionStrings__Database=Host=db;Port=5432;Database=featureflag;Username=postgres;Password=123456
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: featureflag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
